import pandas as pd


def remove_first_csv_column(csv_path) -> None:
    # IMPORTANT:
    # In the csv that's generated by Fiji, the first column is the frame number and thus shouldn't be treated as data!
    # This function can be used to delete it.

    df = pd.read_csv(csv_path)
    if df.columns[0] == ' ':
        df.drop(columns=df.columns[0], axis=1, inplace=True)
    df.to_csv(csv_path, index=False)
