import numpy as np
import pandas as pd

from src.utils.roi_names import roi_indexes_to_imagej_label


def convert_csv_to_array(csv_path, n_horizontal, n_vertical) -> np.array:
    """This function takes the csv file generated by ImageJ and converts it into a numpy array where...
    the first dimension represents the horizontal ROI index,
    the second represents the vertical ROI index,
    and the third represents the frames. The value is the signal.
    """
    df = pd.read_csv(csv_path)

    n_frames = df.shape[0]  # get the number of rows
    arr = np.zeros(shape=(n_horizontal, n_vertical, n_frames))

    for x in range(n_horizontal):
        for y in range(n_vertical):
            col_name = roi_indexes_to_imagej_label(x, y)
            arr[x, y, :] = df[col_name]

    return arr
