import numpy as np
import pandas as pd
import os


def remove_first_csv_column(csv_path):
    # IMPORTANT:
    # In the csv that's generated by Fiji, the first column is the frame number and thus shouldn't be treated as data!
    # This function can be used to delete it.

    df = pd.read_csv(csv_path)
    df.drop(columns=df.columns[0], axis=1, inplace=True)
    df.to_csv(csv_path, index=False)


def convert_csv_to_array(csv_path, n_horizontal, n_vertical) -> np.array:
    """This function takes the csv file generated by ImageJ and converts it into a numpy array where...
    the first dimension represents the horizontal ROI index,
    the second represents the vertical ROI index,
    and the third represents the changing signal through the frames.
    """
    df = pd.read_csv(csv_path)

    n_frames = df.shape[0]  # get the number of rows
    arr = np.zeros(shape=(n_horizontal, n_vertical, n_frames))

    for x in range(n_horizontal):
        for y in range(n_vertical):
            col_name = f'Mean(({x}; {y}))'
            arr[x, y, :] = df[col_name]

    return arr

# high_res_test_stack_dir = '/Users/julian/development/PycharmProjects/glioblastoma/data/01_raw/high_res_test_stack/'
# hrts_csv_path = os.path.join(high_res_test_stack_dir, 'Results.csv')
# arr = convert_csv_to_array(hrts_csv_path, n_horizontal=16, n_vertical=16)
